// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23jWQ8BckReRmuRjXRM4qeeHZDXPjbVU',
    appId: '1:400321097654:web:175b3be3c9101b6d951b17',
    messagingSenderId: '400321097654',
    projectId: 'resqlink-mobile-app',
    authDomain: 'resqlink-mobile-app.firebaseapp.com',
    storageBucket: 'resqlink-mobile-app.firebasestorage.app',
    measurementId: 'G-G163MZZ4BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8JRjxnO6zzadt-V7Bn_jybWDm1nDW7Rk',
    appId: '1:400321097654:android:84ab294870bbc401951b17',
    messagingSenderId: '400321097654',
    projectId: 'resqlink-mobile-app',
    storageBucket: 'resqlink-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOj87n8x_QhI6Z_y7fdCr_eLlF8po_AF0',
    appId: '1:400321097654:ios:03c9517b9a20dcff951b17',
    messagingSenderId: '400321097654',
    projectId: 'resqlink-mobile-app',
    storageBucket: 'resqlink-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
